CONS_VERSION_AGGREGATORS    = 'a0.1'
CONS_VERSION_BLOG           = 'a0.1'
CONS_VERSION_TOOLMODEL      = 'a0.7'
CONS_VERSION_TOOLMODEL_OLD  = 'a0.6'
CONS_VERSION_TASKMODEL      = 'a0.4'
CONS_VERSION_TASKMODEL_OLD  = 'a0.3'
CONS_VERSION_TECHNICALTAG   = 'a0.1'

__all__ = [
    "CONS_VERSION_AGGREGATORS",
    "CONS_VERSION_BLOG",
    "CONS_VERSION_TOOLMODEL_OLD",
    "CONS_VERSION_TOOLMODEL",
    "CONS_VERSION_TASKMODEL_OLD",
    "CONS_VERSION_TASKMODEL",
    "CONS_VERSION_TECHNICALTAG",
    ]

if __name__ == 'main':
    for name_adress, some_adress in zip(
    [
        "CONS_VERSION_AGGREGATORS",
        "CONS_VERSION_BLOG",
        "CONS_VERSION_TOOLMODEL_OLD",
        "CONS_VERSION_TOOLMODEL",
        "CONS_VERSION_TASKMODEL_OLD",
        "CONS_VERSION_TASKMODEL",
        "CONS_VERSION_TECHNICALTAG"
    ],
    [
        CONS_VERSION_AGGREGATORS,
        CONS_VERSION_BLOG,
        CONS_VERSION_TOOLMODEL_OLD,
        CONS_VERSION_TOOLMODEL,
        CONS_VERSION_TASKMODEL_OLD,
        CONS_VERSION_TASKMODEL,
        CONS_VERSION_TECHNICALTAG
    ]):
        print(f'{name_adress}: {some_adress}')